# Generated by Django 2.2 on 2020-12-22 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='text',
            field=models.TextField(default=''),
        ),
    ]
