# Generated by Django 2.2 on 2020-12-22 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0003_pack'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='pack',
            field=models.TextField(default=''),
        ),
    ]
