# Generated by Django 2.2 on 2020-12-22 23:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0004_record_pack'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='pack',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='records.Pack'),
        ),
    ]
