# Generated by Django 2.2 on 2020-12-22 23:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0005_auto_20201223_0755'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='pack',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='records.Pack'),
        ),
    ]
