# Generated by Django 2.2 on 2020-12-28 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0006_auto_20201223_0759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='text',
            field=models.TextField(blank=True, default=''),
        ),
    ]
