# Generated by Django 2.2 on 2020-12-28 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0007_auto_20201228_1231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='text',
            field=models.TextField(default=''),
        ),
    ]
