# Generated by Django 2.2 on 2020-12-29 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0008_auto_20201228_1232'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='record',
            unique_together={('pack', 'text')},
        ),
    ]
